### ISSUE TITLE
Use @content arguments to improve theme mixin

### ISSUE THREAD

**Issue by thetrevorharmon** [thetrevorharmon/thetrevorharmon.com#52]
Libsass 3.6.0 introduces the ability to add arguments to `@content` blocks in mixins. Unfortunately, `node-sass` doesn't have support for 3.6.0 quite yet. Once that has support, it could make for a great `theme` mixin to improve the scss across the site. Something like:

```scss
@mixin theme($selector) {
  $themes: (light, dark);
  @each $theme in $themes {
    .#{$selector}-#{$theme} {
      @content($theme);
    }
  }
}

@include theme(Button) using ($theme) {
  background: color($theme, primary);
}
```
The documentation about this specific thing can be found on the [Sass website.](https://sass-lang.com/documentation/at-rules/mixin#passing-arguments-to-content-blocks)
